# Netlify configuration for SPA routing

[build]
  # Replace 'build' with your actual build output directory if different (e.g., 'dist')
  publish = "build" 
  command = "npm run build" # Or your build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200